added consecutive snapshot count filter to the rds resource
jasgrover/cloud-custodian pull request #1
Opened 2022-03-12 04:28 UTC by jasgrover

2022-03-12 12:45 UTC, darrendao requested changes
nice PR with unit tests. However, there are a couple of issues. See my comments

2022-03-12 12:45 UTC, darrendao commented on c7n/resources/rds.py
> +    schema = type_schema('consecutive-snapshots', days={'type': 'number'})
might want to set constraint on what value `days` can be. For example, we don't want the code to blow up if the user don't provide a value for it or if they pecify a negative number. So maybe change this into
```
    schema = type_schema(
        'consecutive-snapshots',
        days={'type': 'number', 'minimum': 1},
        required=['days']
    )
```
Or make it so that we have a default value for `days` if users don't specify one.

2022-03-12 12:45 UTC, darrendao commented on c7n/resources/rds.py
> +        return results
Try to avoid nested code. One way to do that is to check for the opposite and break out/exit early. For example
```
        if not resources:  # nothing to do
            return results

        for resource in resources:
            if resource['Engine'] not in exclude_engine:
                response = client.describe_db_snapshots(
                    DBInstanceIdentifier=resource['DBInstanceIdentifier'])
                resource.update({'DBSnapshots': response['DBSnapshots']})
                results.append(resource)
        return results
```

Alternatively, you don't even have to explicitly check `resources` and can just do this instead
```
        for resource in resources or []:
            if resource['Engine'] not in exclude_engine:
                response = client.describe_db_snapshots(
                    DBInstanceIdentifier=resource['DBInstanceIdentifier'])
                resource.update({'DBSnapshots': response['DBSnapshots']})
                results.append(resource)
        return results
```

2022-03-12 12:45 UTC, darrendao commented on c7n/resources/rds.py
> +        exclude_engine = self.data.get('exclude_engine', [])
Where is `exclude_engine` defined? I don't see it in the schema

2022-03-12 12:45 UTC, darrendao commented on c7n/resources/rds.py
> +            print(resource)
i assume this is for debugging. Remember to remove

2022-03-12 12:45 UTC, darrendao commented on c7n/resources/rds.py
> +        for i in range(retention - 1):
not sure if this has the right logic. Supposed `days` = 3, then this filter should match if there are at least 3 snapshots. However, with `retention - 1`, we would only have 2 dates in `expectedDates`, causing the filter to match even if there are only 2 snapshots.

2022-03-12 12:45 UTC, darrendao commented on c7n/resources/rds.py
> +                    if snapshot['Status'] == 'available':
This will blow up if `resource` doesn't have `DBSnapshots` key. I think you want to do
```
if resource.get('DBSnapshots'):
```

Also as mentioned, avoid deeply nested code. You have an if, inside a for, inside an if, inside a for.

Maybe rewrite it as
```
        for resource in self.enhance_resources(resources):
            if not resource.get('DBSnapshots'):
                continue
            snapshot_dates = []
            for snapshot in resource['DBSnapshots']:
                if snapshot['Status'] == 'available':
                    snapshot_dates.append(snapshot['SnapshotCreateTime'].strftime('%Y-%m-%d'))
            if set(expectedDates).issubset(snapshot_dates):
                results.append(resource)
```

2022-03-12 18:05 UTC, jasgrover commented on c7n/resources/rds.py
> +    schema = type_schema('consecutive-snapshots', days={'type': 'number'})
great suggestion .. many thanks . I added the exclude_engine to schema which i had  missed

2022-03-12 18:05 UTC, jasgrover commented on c7n/resources/rds.py
> +        return results
removed redundant check

2022-03-12 18:05 UTC, jasgrover commented on c7n/resources/rds.py
> +            print(resource)
fixed

2022-03-12 18:06 UTC, jasgrover commented on c7n/resources/rds.py
> +                    if snapshot['Status'] == 'available':
yep .. fixed.

2022-03-12 18:06 UTC, jasgrover commented on c7n/resources/rds.py
> +        for i in range(retention - 1):
now looking back .. not sure what i was thinking !!

2022-03-12 18:07 UTC, jasgrover commented on c7n/resources/rds.py
> +        exclude_engine = self.data.get('exclude_engine', [])
fixed

2022-03-14 18:13 UTC, darrendao commented on c7n/resources/rdscluster.py
> +class ConsecutiveSnapshots(Filter):
@jasgrover code is almost identical to the other one. Look into how you can re-use code

2022-03-14 19:03 UTC, darrendao commented on c7n/resources/rdscluster.py
> +     exclude_engine={'type': 'array', 'items': {'type': 'string'}}, required=['days'])
@jasgrover indentation here seems off

2022-03-14 19:05 UTC, darrendao commented on c7n/resources/rds.py
> +     exclude_engine={'type': 'array', 'items': {'type': 'string'}}, required=['days'])
@jasgrover i think it should be `exclude_engines` plural since it's an array

2022-03-15 14:32 UTC, jasgrover commented on c7n/resources/rds.py
> +     exclude_engine={'type': 'array', 'items': {'type': 'string'}}, required=['days'])
fixed

2022-03-15 14:32 UTC, jasgrover commented on c7n/resources/rdscluster.py
> +     exclude_engine={'type': 'array', 'items': {'type': 'string'}}, required=['days'])
lint comes out clean

2022-03-15 14:35 UTC, jasgrover commented on c7n/resources/rds.py
> +            if set(expectedDates).issubset(snapshot_dates):
fixed

2022-03-16 19:35 UTC, merged